root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
full_bin = "./tmp/main web"
include_ext = ["go", "sql", "html"]
exclude_dir = ["_tmpdb", "tmp", "node_modules"]

