package presentation

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/kokizzu/gotro/L"

	"indexer/domain"
)

//go:generate go test -run '^$' -bench=BenchmarkGenerateViews

const generatedComment = "\n// Code generated by 1_codegen_test.go DO NOT EDIT.\n"

type routeSpec struct {
	ActionConst string
	Method      string
	Handler     string
}

type cmdSpec struct {
	ActionConst string
	InType      string
	ExecCall    string
	OutMode     string // out|outRc
}

func BenchmarkGenerateViews(b *testing.B) {
	routes := []routeSpec{
		{`StatusAction`, `Get`, `statusHandler`},
		{`ReindexAction`, `Post`, `reindexHandler`},
		{`BrowseAction`, `Get`, `browseHandler`},
		{`OpenAction`, `Get`, `openHandler`},
		{`DuplicatesAction`, `Get`, `duplicatesHandler`},
		{`SearchAction`, `Get`, `searchHandler`},
		{`SuggestAction`, `Post`, `suggestHandler`},
		{`SuggestSubtitleAction`, `Post`, `suggestSubtitleHandler`},
		{`ScanSubtitlesAction`, `Post`, `scanSubtitlesHandler`},
		{`CategorizePreviewAction`, `Post`, `categorizePreviewHandler`},
		{`MoveAction`, `Post`, `moveHandler`},
		{`RenameAction`, `Post`, `renameHandler`},
		{`DeleteAction`, `Post`, `deleteHandler`},
		{`ManageQueueAction`, `Post`, `manageQueueHandler`},
		{`ManageCancelAction`, `Post`, `manageCancelHandler`},
		{`ManageRetryAction`, `Post`, `manageRetryHandler`},
		{`ManageStatusAction`, `Get`, `manageStatusHandler`},
		{`ManageHistoryAction`, `Get`, `manageHistoryHandler`},
		{`BackupConfigAction`, `Get`, `backupConfigHandler`},
		{`BackupEstimateAction`, `Get`, `backupEstimateHandler`},
		{`BackupRunAction`, `Post`, `backupRunHandler`},
	}
	cmds := []cmdSpec{
		{`StatusAction`, `StatusIn`, `execStatus(in, d)`, `out`},
		{`ReindexAction`, `ReindexIn`, `execReindex(in, d)`, `out`},
		{`BrowseAction`, `BrowseIn`, `execBrowse(in, d)`, `outRc`},
		{`DuplicatesAction`, `DuplicatesIn`, `execDuplicates(in, d)`, `outRc`},
		{`SearchAction`, `SearchIn`, `execSearch(&in, d)`, `out`},
		{`SuggestAction`, `SuggestIn`, `execSuggest(&in, d)`, `out`},
		{`SuggestSubtitleAction`, `SuggestIn`, `execSuggestSubtitle(&in, d)`, `out`},
		{`ScanSubtitlesAction`, `SubtitleScanIn`, `execScanSubtitles(&in, d)`, `outRc`},
		{`CategorizePreviewAction`, `CategorizePreviewIn`, `execCategorizePreview(in, d)`, `out`},
		{`MoveAction`, `MoveIn`, `execMove(&in, d)`, `out`},
		{`RenameAction`, `RenameIn`, `execRename(&in, d)`, `out`},
		{`DeleteAction`, `DeleteIn`, `execDelete(&in, d)`, `out`},
		{`ManageQueueAction`, `ManageQueueIn`, `execManageQueue(in, d)`, `out`},
		{`ManageCancelAction`, `ManageQueueIn`, `execManageCancel(in, d)`, `out`},
		{`ManageRetryAction`, `ManageQueueIn`, `execManageRetry(in, d)`, `out`},
		{`ManageStatusAction`, `ManageStatusIn`, `execManageStatus(in, d)`, `out`},
		{`ManageHistoryAction`, `ManageHistoryIn`, `execManageHistory(&in, d)`, `outRc`},
		{`BackupConfigAction`, `BackupConfigIn`, `execBackupConfig(in, d)`, `out`},
		{`BackupEstimateAction`, `BackupEstimateIn`, `execBackupEstimate(in, d)`, `out`},
		{`BackupRunAction`, `BackupRunIn`, `execBackupRun(in, d)`, `out`},
	}

	writeGenerated("actions.GEN.go", generateActions())
	writeGenerated("api_routes.GEN.go", generateApiRoutes(routes))
	writeGenerated("cmd_run.GEN.go", generateCmdRun(cmds))
	writeGenerated("web_view.GEN.go", generateWebView())
	writeGenerated(filepath.Join("..", "svelte", "jsApi.GEN.js"), generateJsApi(routes))

	b.SkipNow()
}

func writeGenerated(path string, body string) {
	err := os.WriteFile(path, []byte(body), 0o644)
	L.PanicIf(err, `write generated file: `+path)
}

func generateActions() string {
	var b bytes.Buffer
	b.WriteString("package presentation\n")
	b.WriteString(generatedComment)
	b.WriteString("\nimport \"indexer/domain\"\n\n")
	b.WriteString("var allCommands = domain.AllActions\n")
	return b.String()
}

func generateApiRoutes(routes []routeSpec) string {
	var b bytes.Buffer
	b.WriteString("package presentation\n")
	b.WriteString(generatedComment)
	b.WriteString("\nimport (\n\t\"indexer/domain\"\n\n\t\"github.com/gofiber/fiber/v2\"\n)\n\n")
	b.WriteString("func ApiRoutes(app *fiber.App, d *domain.Domain) {\n")
	for _, rt := range routes {
		b.WriteString("\tapp." + rt.Method + "(\"/api/\"+domain." + rt.ActionConst + ", " + rt.Handler + "(d))\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func generateCmdRun(cmds []cmdSpec) string {
	var b bytes.Buffer
	b.WriteString("package presentation\n")
	b.WriteString(generatedComment)
	b.WriteString("\nimport (\n\t\"bytes\"\n\n\t\"indexer/domain\"\n)\n\n")
	b.WriteString("func cmdRun(d *domain.Domain, stdout *bytes.Buffer, stderr *bytes.Buffer, action string, payload []byte) int {\n")
	b.WriteString("\tswitch action {\n")
	for _, cmd := range cmds {
		b.WriteString("\tcase domain." + cmd.ActionConst + ":\n")
		b.WriteString("\t\tin := domain." + cmd.InType + "{}\n")
		b.WriteString("\t\tif !in.RequestCommon.FromCli(action, payload, &in) {\n\t\t\treturn 1\n\t\t}\n")
		if cmd.OutMode == "out" {
			b.WriteString("\t\tout := " + cmd.ExecCall + "\n")
			b.WriteString("\t\tin.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)\n")
			b.WriteString("\t\treturn statusCodeToExit(out.ResponseCommon.StatusCode)\n")
		} else {
			b.WriteString("\t\tout, rc := " + cmd.ExecCall + "\n")
			b.WriteString("\t\tin.RequestCommon.ToCli(stdout, stderr, out, rc)\n")
			b.WriteString("\t\treturn statusCodeToExit(rc.StatusCode)\n")
		}
	}
	b.WriteString("\tdefault:\n\t\treturn 2\n\t}\n}\n\n")
	b.WriteString("func statusCodeToExit(code int) int {\n\tif code >= 400 {\n\t\treturn 1\n\t}\n\treturn 0\n}\n")
	return b.String()
}

func generateWebView() string {
	return `package presentation
` + generatedComment + `
import (
	"os"

	"github.com/gofiber/fiber/v2"
)

var viewList = map[string]string{
	` + "`Index`" + `: ` + "`../svelte/index.html`" + `,
}

type Views struct{}

func (v *Views) LoadAll() {
}

func (v *Views) RenderIndex(c *fiber.Ctx) error {
	data, err := os.ReadFile(builtSveltePath("index.html"))
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).SendString(err.Error())
	}
	c.Set(fiber.HeaderContentType, "text/html; charset=utf-8")
	return c.Send(data)
}
`
}

func generateJsApi(routes []routeSpec) string {
	keys := map[string]string{
		`StatusAction`:            `status`,
		`ReindexAction`:           `reindex`,
		`BrowseAction`:            `browse`,
		`OpenAction`:              `open`,
		`DuplicatesAction`:        `duplicates`,
		`SearchAction`:            `search`,
		`SuggestAction`:           `suggest`,
		`SuggestSubtitleAction`:   `suggestSubtitle`,
		`ScanSubtitlesAction`:     `scanSubtitles`,
		`CategorizePreviewAction`: `categorizePreview`,
		`MoveAction`:              `move`,
		`RenameAction`:            `rename`,
		`DeleteAction`:            `delete`,
		`ManageQueueAction`:       `manageQueue`,
		`ManageCancelAction`:      `manageCancel`,
		`ManageRetryAction`:       `manageRetry`,
		`ManageStatusAction`:      `manageStatus`,
		`ManageHistoryAction`:     `manageHistory`,
		`BackupConfigAction`:      `backupConfig`,
		`BackupEstimateAction`:    `backupEstimate`,
		`BackupRunAction`:         `backupRun`,
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by 1_codegen_test.go DO NOT EDIT.\n\n")
	b.WriteString("export const IndexerApi = {\n")
	for _, rt := range routes {
		b.WriteString("  " + keys[rt.ActionConst] + ": '/api/" + actionValue(rt.ActionConst) + "',\n")
	}
	b.WriteString("};\n\n")
	b.WriteString("export default IndexerApi;\n\n")
	b.WriteString(";(function (global) {\n")
	b.WriteString("  global.IndexerApi = IndexerApi;\n")
	b.WriteString("})(typeof window !== 'undefined' ? window : globalThis);\n")
	return b.String()
}

func actionValue(actionConst string) string {
	switch actionConst {
	case "StatusAction":
		return domain.StatusAction
	case "ReindexAction":
		return domain.ReindexAction
	case "BrowseAction":
		return domain.BrowseAction
	case "OpenAction":
		return domain.OpenAction
	case "DuplicatesAction":
		return domain.DuplicatesAction
	case "SearchAction":
		return domain.SearchAction
	case "SuggestAction":
		return domain.SuggestAction
	case "SuggestSubtitleAction":
		return domain.SuggestSubtitleAction
	case "ScanSubtitlesAction":
		return domain.ScanSubtitlesAction
	case "CategorizePreviewAction":
		return domain.CategorizePreviewAction
	case "MoveAction":
		return domain.MoveAction
	case "RenameAction":
		return domain.RenameAction
	case "DeleteAction":
		return domain.DeleteAction
	case "ManageQueueAction":
		return domain.ManageQueueAction
	case "ManageCancelAction":
		return domain.ManageCancelAction
	case "ManageRetryAction":
		return domain.ManageRetryAction
	case "ManageStatusAction":
		return domain.ManageStatusAction
	case "ManageHistoryAction":
		return domain.ManageHistoryAction
	case "BackupConfigAction":
		return domain.BackupConfigAction
	case "BackupEstimateAction":
		return domain.BackupEstimateAction
	case "BackupRunAction":
		return domain.BackupRunAction
	default:
		return ""
	}
}
