package presentation

// Code generated by 1_codegen_test.go DO NOT EDIT.

import (
	"indexer/domain"

	"github.com/gofiber/fiber/v2"
)

func ApiRoutes(app *fiber.App, d *domain.Domain) {
	app.Get("/api/"+domain.StatusAction, statusHandler(d))
	app.Post("/api/"+domain.ReindexAction, reindexHandler(d))
	app.Get("/api/"+domain.BrowseAction, browseHandler(d))
	app.Get("/api/"+domain.OpenAction, openHandler(d))
	app.Get("/api/"+domain.DuplicatesAction, duplicatesHandler(d))
	app.Get("/api/"+domain.SearchAction, searchHandler(d))
	app.Post("/api/"+domain.SuggestAction, suggestHandler(d))
	app.Post("/api/"+domain.SuggestSubtitleAction, suggestSubtitleHandler(d))
	app.Post("/api/"+domain.ScanSubtitlesAction, scanSubtitlesHandler(d))
	app.Post("/api/"+domain.CategorizePreviewAction, categorizePreviewHandler(d))
	app.Post("/api/"+domain.MoveAction, moveHandler(d))
	app.Post("/api/"+domain.RenameAction, renameHandler(d))
	app.Post("/api/"+domain.DeleteAction, deleteHandler(d))
	app.Post("/api/"+domain.ManageQueueAction, manageQueueHandler(d))
	app.Post("/api/"+domain.ManageCancelAction, manageCancelHandler(d))
	app.Post("/api/"+domain.ManageRetryAction, manageRetryHandler(d))
	app.Get("/api/"+domain.ManageStatusAction, manageStatusHandler(d))
	app.Get("/api/"+domain.ManageHistoryAction, manageHistoryHandler(d))
	app.Get("/api/"+domain.BackupConfigAction, backupConfigHandler(d))
	app.Get("/api/"+domain.BackupEstimateAction, backupEstimateHandler(d))
	app.Post("/api/"+domain.BackupRunAction, backupRunHandler(d))
}
