package presentation

// Code generated by 1_codegen_test.go DO NOT EDIT.

import (
	"bytes"

	"indexer/domain"
)

func cmdRun(d *domain.Domain, stdout *bytes.Buffer, stderr *bytes.Buffer, action string, payload []byte) int {
	switch action {
	case domain.StatusAction:
		in := domain.StatusIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out := execStatus(in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)
		return statusCodeToExit(out.ResponseCommon.StatusCode)
	case domain.ReindexAction:
		in := domain.ReindexIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out := execReindex(in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)
		return statusCodeToExit(out.ResponseCommon.StatusCode)
	case domain.BrowseAction:
		in := domain.BrowseIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out, rc := execBrowse(in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, rc)
		return statusCodeToExit(rc.StatusCode)
	case domain.DuplicatesAction:
		in := domain.DuplicatesIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out, rc := execDuplicates(in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, rc)
		return statusCodeToExit(rc.StatusCode)
	case domain.SearchAction:
		in := domain.SearchIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out := execSearch(&in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)
		return statusCodeToExit(out.ResponseCommon.StatusCode)
	case domain.SuggestAction:
		in := domain.SuggestIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out := execSuggest(&in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)
		return statusCodeToExit(out.ResponseCommon.StatusCode)
	case domain.SuggestSubtitleAction:
		in := domain.SuggestIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out := execSuggestSubtitle(&in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)
		return statusCodeToExit(out.ResponseCommon.StatusCode)
	case domain.ScanSubtitlesAction:
		in := domain.SubtitleScanIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out, rc := execScanSubtitles(&in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, rc)
		return statusCodeToExit(rc.StatusCode)
	case domain.CategorizePreviewAction:
		in := domain.CategorizePreviewIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out := execCategorizePreview(in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)
		return statusCodeToExit(out.ResponseCommon.StatusCode)
	case domain.MoveAction:
		in := domain.MoveIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out := execMove(&in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)
		return statusCodeToExit(out.ResponseCommon.StatusCode)
	case domain.RenameAction:
		in := domain.RenameIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out := execRename(&in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)
		return statusCodeToExit(out.ResponseCommon.StatusCode)
	case domain.DeleteAction:
		in := domain.DeleteIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out := execDelete(&in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)
		return statusCodeToExit(out.ResponseCommon.StatusCode)
	case domain.ManageQueueAction:
		in := domain.ManageQueueIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out := execManageQueue(in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)
		return statusCodeToExit(out.ResponseCommon.StatusCode)
	case domain.ManageCancelAction:
		in := domain.ManageQueueIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out := execManageCancel(in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)
		return statusCodeToExit(out.ResponseCommon.StatusCode)
	case domain.ManageRetryAction:
		in := domain.ManageQueueIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out := execManageRetry(in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)
		return statusCodeToExit(out.ResponseCommon.StatusCode)
	case domain.ManageStatusAction:
		in := domain.ManageStatusIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out := execManageStatus(in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, out.ResponseCommon)
		return statusCodeToExit(out.ResponseCommon.StatusCode)
	case domain.ManageHistoryAction:
		in := domain.ManageHistoryIn{}
		if !in.RequestCommon.FromCli(action, payload, &in) {
			return 1
		}
		out, rc := execManageHistory(&in, d)
		in.RequestCommon.ToCli(stdout, stderr, out, rc)
		return statusCodeToExit(rc.StatusCode)
	default:
		return 2
	}
}

func statusCodeToExit(code int) int {
	if code >= 400 {
		return 1
	}
	return 0
}
