package presentation

// Code generated by 1_codegen_test.go DO NOT EDIT.

import (
	"os"

	"github.com/gofiber/fiber/v2"
)

var viewList = map[string]string{
	`Index`: `../svelte/index.html`,
}

type Views struct{}

func (v *Views) LoadAll() {
}

func (v *Views) RenderIndex(c *fiber.Ctx) error {
	data, err := os.ReadFile(builtSveltePath("index.html"))
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).SendString(err.Error())
	}
	c.Set(fiber.HeaderContentType, "text/html; charset=utf-8")
	return c.Send(data)
}
