// Code generated by 1_codegen_test.go DO NOT EDIT.

export const IndexerApi = {
  status: '/api/status',
  reindex: '/api/reindex',
  browse: '/api/browse',
  duplicates: '/api/duplicates',
  search: '/api/search',
  suggest: '/api/suggest',
  suggestSubtitle: '/api/suggest-subtitle',
  scanSubtitles: '/api/scan-subtitles',
  categorizePreview: '/api/categorize/preview',
  move: '/api/move',
  rename: '/api/rename',
  delete: '/api/delete',
  manageQueue: '/api/manage/queue',
  manageCancel: '/api/manage/cancel',
  manageRetry: '/api/manage/retry',
  manageStatus: '/api/manage/status',
  manageHistory: '/api/manage/history',
};

export default IndexerApi;
